# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: gwpicard
email: gwpicard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 gwpicard website
baseurl: "/gwpicard" # the subpath of your site, e.g. /blog
url: "http://gwpicard.com" # the base hostname & protocol for your site
twitter_username: gwpicard
github_username:  gwpicard
facebook_username: williamsampicard
linkedin_username: gwpicard


# Build settings
markdown: kramdown
